import { describe, it, expect } from 'vitest';
import { onlyDigits, isValidCpf, isValidEmailStrict } from './validators';

describe('validators', () => {
  describe('onlyDigits', () => {
    it('should strip all non-digit characters from a string', () => {
      expect(onlyDigits('123.456.789-00')).toBe('12345678900');
      expect(onlyDigits('(11) 98765-4321')).toBe('11987654321');
      expect(onlyDigits('abc-123_xyz')).toBe('123');
      expect(onlyDigits('')).toBe('');
    });
  });

  describe('isValidCpf', () => {
    it('should return true for mathematically valid CPFs', () => {
      // Valid CPFs generated by standard algorithms
      expect(isValidCpf('52998224725')).toBe(true);
      expect(isValidCpf('529.982.247-25')).toBe(true); // handles formatting by stripping it
      expect(isValidCpf('24483911066')).toBe(true);
      expect(isValidCpf('244.839.110-66')).toBe(true);
    });

    it('should return false for CPFs with invalid lengths', () => {
      expect(isValidCpf('1234567890')).toBe(false); // 10 digits
      expect(isValidCpf('123456789012')).toBe(false); // 12 digits
      expect(isValidCpf('')).toBe(false);
    });

    it('should return false for mathematically invalid checking digits', () => {
      // Correct length but mathematically invalid checking digits
      expect(isValidCpf('52998224726')).toBe(false); // Last digit changed from 5 to 6
      expect(isValidCpf('24483911067')).toBe(false); // Last digit changed from 6 to 7
    });

    it('should return false for repeating digits patterns', () => {
      // Repeating digits are mathematically valid under modulo 11 but invalid in real life
      expect(isValidCpf('00000000000')).toBe(false);
      expect(isValidCpf('11111111111')).toBe(false);
      expect(isValidCpf('99999999999')).toBe(false);
      expect(isValidCpf('000.000.000-00')).toBe(false);
    });
  });

  describe('isValidEmailStrict', () => {
    it('should return true for valid email formats', () => {
      expect(isValidEmailStrict('user@example.com')).toBe(true);
      expect(isValidEmailStrict('first.last@company.com.br')).toBe(true);
      expect(isValidEmailStrict('user-name@domain-name.org')).toBe(true);
      expect(isValidEmailStrict('a@b.co')).toBe(true);
    });

    it('should return false for invalid email formats', () => {
      expect(isValidEmailStrict('plainaddress')).toBe(false);
      expect(isValidEmailStrict('#@%^%#$@#$@#.com')).toBe(false);
      expect(isValidEmailStrict('@example.com')).toBe(false);
      expect(isValidEmailStrict('Joe Smith <email@example.com>')).toBe(false);
      expect(isValidEmailStrict('email.example.com')).toBe(false);
      expect(isValidEmailStrict('email@example@example.com')).toBe(false);
      expect(isValidEmailStrict('email@example.com.')).toBe(false);
      expect(isValidEmailStrict('email@example.com ')).toBe(false); // trailing space
      expect(isValidEmailStrict(' email@example.com')).toBe(false); // leading space
      
      // Strict cases
      expect(isValidEmailStrict('cliente@.com')).toBe(false);
      expect(isValidEmailStrict('cliente@domain.')).toBe(false);
    });
  });
});
